vim.cmd('filetype plugin indent on')
vim.o.scrolloff = 3
vim.o.sidescrolloff = 5
vim.o.mouse = "a"
vim.o.cursorline = true
vim.o.fileencoding = 'utf-8'
vim.o.whichwrap = 'b,s,<,>,[,],h,l'
vim.o.pumheight = 10
vim.o.hlsearch = true
vim.o.ignorecase =true
vim.o.showmode = false
vim.opt.termguicolors = true
vim.wo.number = true
vim.o.shiftwidth = 2
vim.bo.shiftwidth = 2
vim.o.tabstop = 2
vim.bo.tabstop = 2
vim.o.softtabstop = 2
vim.o.expandtab = true
vim.bo.expandtab = true
vim.o.showtabline = 2
vim.o.cmdheight = 1 
vim.o.shortmess = vim.o.shortmess .. 'c'
vim.o.splitbelow = true
vim.o.splitright = true
vim.wo.wrap = false
vim.wo.signcolumn = "yes"
-- vim.o.cursorcolumn = true
